### ISSUE TITLE
Freedom Book Possibility

### ISSUE THREAD

**Issue by AiryTheDragon** [Endtime-Entrepreneurs/GameJam7#75]
"Bug" Category: Feature Request
Severity: Minor effects to game play

Describe the bug:
Freedom books should do something useful

Describe what you expect
I request another type of letter.  If you have a freedom book, you can write a letter to an NPC/Guard, and given them the letter&book in exchange for 2 morale

**Comment by DaDarkWizard** [comment]
This will be worked on alongside revamping the writing table

**Comment by AiryTheDragon** [comment]
Freedom books are now included in the inventory.
