### ISSUE TITLE
Isaac Movement Error

### ISSUE THREAD

**Issue by AiryTheDragon** [Endtime-Entrepreneurs/GameJam7#76]
"Bug" Category:  Bug/Unexpected Behavior

Severity: Superficial/isolated

Describe the bug:
Isaac no longer runs around the room, but just circles around the light

Describe what you expect:
He should run around the room, similar to Autumn

**Comment by DaDarkWizard** [comment]
We don't know what's happening.
Maybe something with AI
I think he can't reach his goal for walking
