### ISSUE TITLE
Add a tutorial

### ISSUE THREAD

**Issue by AiryTheDragon** [Endtime-Entrepreneurs/GameJam7#85]
To help gamers adjust to the game, there would be a tutorial to go over the basic concepts of the game.

**Comment by DaDarkWizard** [comment]
Fixes #63

**Comment by AiryTheDragon** [comment]
The tutorial was added, but needs to be reviewed and tested for improvements.

**Comment by AiryTheDragon** [comment]
Tutorial is added.  It needs testing, but this will be closed for now.
